FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        ca-certificates \
        sudo \
        python3-pip \
        tzdata && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    update-ca-certificates && \
    apt-get remove -y meson || true && \
    pip3 install meson && \
    rm -rf /var/lib/apt/lists/*

COPY . /opt/aamp

WORKDIR /opt/aamp
ENV CMAKE_POLICY_VERSION_MINIMUM=3.5

RUN bash -c '\
  set -euo pipefail && \
  export LOCAL_DEPS_BUILD_DIR=/opt/local_deps && \
  mkdir -p "$LOCAL_DEPS_BUILD_DIR" && \
  source scripts/tools.sh && \
  source scripts/install_clone.sh && \
  source scripts/install_dir.sh && \
  source scripts/install_dependencies.sh && \
  source scripts/install_gtest.sh && \
  source scripts/install_libdash.sh && \
  install_pkgs_fn  && \
  install_build_googletest_fn true && \
  install_build_libdash_fn true \
'

RUN rm -rf /opt/aamp

ENV LOCAL_DEPS_BUILD_DIR=/opt/local_deps
ENV PKG_CONFIG_PATH=$LOCAL_DEPS_BUILD_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH=$LOCAL_DEPS_BUILD_DIR/lib:$LD_LIBRARY_PATH
ENV CMAKE_PREFIX_PATH=$LOCAL_DEPS_BUILD_DIR:$CMAKE_PREFIX_PATH
ENV CPLUS_INCLUDE_PATH=$LOCAL_DEPS_BUILD_DIR/include:$CPLUS_INCLUDE_PATH
ENV C_INCLUDE_PATH=$LOCAL_DEPS_BUILD_DIR/include:$C_INCLUDE_PATH
ENV LIBRARY_PATH=$LOCAL_DEPS_BUILD_DIR/lib:$LIBRARY_PATH
RUN echo "/opt/local_deps/lib" > /etc/ld.so.conf.d/local_deps.conf && ldconfig

WORKDIR /workspace