FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        ca-certificates \
        sudo \
        python3-pip \
        tzdata && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    update-ca-certificates && \
    apt-get remove -y meson || true && \
    pip3 install meson && \
    rm -rf /var/lib/apt/lists/*

COPY . /opt/aamp

WORKDIR /opt/aamp
ENV CMAKE_POLICY_VERSION_MINIMUM=3.5

RUN bash -c '\
  set -euo pipefail && \
  export LOCAL_DEPS_BUILD_DIR=/opt/local_deps && \
  mkdir -p "$LOCAL_DEPS_BUILD_DIR" && \
  source scripts/tools.sh && \
  source scripts/install_clone.sh && \
  source scripts/install_dir.sh && \
  source scripts/install_dependencies.sh && \
  source scripts/install_gtest.sh && \
  source scripts/install_libdash.sh && \
  install_pkgs_fn  && \
  install_build_googletest_fn true && \
  install_build_libdash_fn true \
'

RUN rm -rf /opt/aamp

ENV LOCAL_DEPS_BUILD_DIR=/opt/local_deps
ENV PKG_CONFIG_PATH=$LOCAL_DEPS_BUILD_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH=$LOCAL_DEPS_BUILD_DIR/lib:$LD_LIBRARY_PATH
ENV CMAKE_PREFIX_PATH=$LOCAL_DEPS_BUILD_DIR:$CMAKE_PREFIX_PATH
ENV CPLUS_INCLUDE_PATH=$LOCAL_DEPS_BUILD_DIR/include:$CPLUS_INCLUDE_PATH
ENV C_INCLUDE_PATH=$LOCAL_DEPS_BUILD_DIR/include:$C_INCLUDE_PATH
ENV LIBRARY_PATH=$LOCAL_DEPS_BUILD_DIR/lib:$LIBRARY_PATH
RUN echo "/opt/local_deps/lib" > /etc/ld.so.conf.d/local_deps.conf && ldconfig

# ENV CXXFLAGS="-std=c++17"
# ENV CFLAGS="-std=c17"

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     # Core tools
#     git \
#     cmake \
#     gcc \
#     g++ \
#     build-essential \
#     ninja-build \
#     pkg-config \
#     curl \
#     jq \
#     xz-utils \
#     lcov \
#     gcovr \
#     snapd \
#     openjdk-17-jre-headless \
#     meson \
#     # SSL / crypto / compression
#     libssl-dev \
#     zlib1g-dev \
#     # Networking / JSON / XML
#     libcurl4-openssl-dev \
#     libxml2-dev \
#     libcjson-dev \
#     libjansson-dev \
#     libjsoncpp-dev \
#     libtinyxml2-dev \
#     # Terminal / readline
#     libreadline-dev \
#     # System / misc
#     libglib2.0-dev \
#     libsystemd-dev \
#     libasio-dev \
#     # Graphics / OpenGL
#     freeglut3-dev \
#     libglew-dev \
#     libfontconfig-dev \
#     libharfbuzz-dev \
#     # Boost / testing
#     libboost-all-dev \
#     libcppunit-dev \
#     # Wayland / input
#     libwayland-dev \
#     wayland-protocols \
#     libxkbcommon-dev \
#     # WebSockets
#     libwebsocketpp-dev \
#     # JavaScriptCore / WebKitGTK
#     libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev \
#     # GStreamer dev headers
#     libgstreamer1.0-dev \
#     libgstreamer-plugins-base1.0-dev \
#     libgstreamer-plugins-bad1.0-dev \
#     #gtest
#     libgtest-dev \
#     libgmock-dev \
#     # GStreamer runtime + plugins
#     gstreamer1.0-tools \
#     gstreamer1.0-plugins-base \
#     gstreamer1.0-plugins-good \
#     gstreamer1.0-plugins-bad \
#     gstreamer1.0-plugins-ugly \
#     gstreamer1.0-libav \
#     gstreamer1.0-x \
#     gstreamer1.0-alsa \
#     gstreamer1.0-gl \
#     gstreamer1.0-pulseaudio \
#     && rm -rf /var/lib/apt/lists/*

# # Set environment variables for libdash build
# ENV CXXFLAGS="-std=c++17"
# ENV CFLAGS="-std=c17"
# WORKDIR /tmp

# ENV LOCAL_DEPS_BUILD_DIR=/opt/local_deps
# RUN mkdir -p $LOCAL_DEPS_BUILD_DIR

# # ----------------------
# # Build libdash
# # ----------------------
# RUN cd /opt && \
#     git clone https://github.com/bitmovin/libdash.git && \
#     cd libdash/libdash && \
#     git checkout stable_3_0 && \
#     git clone -b rdk-next https://code.rdkcentral.com/r/rdk/components/generic/rdk-oe/meta-rdk-ext && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0001-libdash-build.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0002-libdash-starttime-uint64.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0003-libdash-presentationTimeOffset-uint64.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0004-Support-of-EventStream.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0005-DELIA-39460-libdash-memleak.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0006-RDK-32003-LLD-Support.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0007-DELIA-51645-Event-Stream-RawAttributes-Support.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0008-DELIA-53263-Use-Label-TAG.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0009-RDK-35134-Support-for-FailoverContent.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0010-RDKAAMP-121-Failover-Tag-on-SegmentTemplate.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0011-RDKAAMP-61-AAMP-low-latency-dash-stream-evaluation.patch && \
#     patch -p1 < meta-rdk-ext/recipes-multimedia/libdash/libdash/0012-To-retrieves-the-text-content-of-CDATA-section.patch && \
#     mkdir -p build && \
#     cd build && \
#     cmake .. -DCMAKE_INSTALL_PREFIX=${LOCAL_DEPS_BUILD_DIR} -DCMAKE_MACOSX_RPATH=TRUE && \
#     make -j$(nproc) && \
#     make install && \
#     cd .. && \
#     mkdir -p \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash/xml \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash/mpd \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash/network \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash/portable \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash/helpers \
#         $LOCAL_DEPS_BUILD_DIR/include/libdash/metrics && \
#     cp -p libdash/include/* $LOCAL_DEPS_BUILD_DIR/include/libdash && \
#     cp -p libdash/source/xml/*.h $LOCAL_DEPS_BUILD_DIR/include/libdash/xml && \
#     cp -p libdash/source/mpd/*.h $LOCAL_DEPS_BUILD_DIR/include/libdash/mpd && \
#     cp -p libdash/source/network/*.h $LOCAL_DEPS_BUILD_DIR/include/libdash/network && \
#     cp -p libdash/source/portable/*.h $LOCAL_DEPS_BUILD_DIR/include/libdash/portable && \
#     cp -p libdash/source/helpers/*.h $LOCAL_DEPS_BUILD_DIR/include/libdash/helpers && \
#     cp -p libdash/source/metrics/*.h $LOCAL_DEPS_BUILD_DIR/include/libdash/metrics && \
#     mkdir -p $LOCAL_DEPS_BUILD_DIR/lib/pkgconfig && \
#     printf "prefix=%s\nexec_prefix=%s\nlibdir=%s/lib\nincludedir=%s/include/libdash\n\nName: libdash\nDescription: ISO/IEC MPEG-DASH library\nVersion: 3.0\nRequires: libxml-2.0\nLibs: -L\${libdir} -ldash\nLibs.private: -lxml2\nCflags: -I\${includedir}\n" \
#         "$LOCAL_DEPS_BUILD_DIR" "$LOCAL_DEPS_BUILD_DIR" "$LOCAL_DEPS_BUILD_DIR" "$LOCAL_DEPS_BUILD_DIR" \
#         > $LOCAL_DEPS_BUILD_DIR/lib/pkgconfig/libdash.pc

# # ======================
# # Build GoogleTest (gtest + gmock)
# # ======================
# RUN git clone https://github.com/google/googletest.git && \
#     cd googletest && \
#     git checkout tags/release-1.11.0 && \
#     mkdir -p build && cd build && \
#     cmake .. -DCMAKE_INSTALL_PREFIX=${LOCAL_DEPS_BUILD_DIR} -DCMAKE_CXX_FLAGS="${CXXFLAGS}" && \
#     make -j$(nproc) && make install

# ENV LOCAL_DEPS_BUILD_DIR=/opt/local_deps
# ENV PKG_CONFIG_PATH=/opt/local_deps/lib/pkgconfig
# ENV CPLUS_INCLUDE_PATH=/opt/local_deps/include
# ENV C_INCLUDE_PATH=/opt/local_deps/include
# ENV LIBRARY_PATH=/opt/local_deps/lib
# ENV LD_LIBRARY_PATH=/opt/local_deps/lib


WORKDIR /workspace
# # ENV PKG_CONFIG_PATH=${LOCAL_DEPS_BUILD_DIR}/lib/pkgconfig:$PKG_CONFIG_PATH
# ENV CMAKE_PREFIX_PATH=${LOCAL_DEPS_BUILD_DIR}:$CMAKE_PREFIX_PATH
# ENV PATH=${LOCAL_DEPS_BUILD_DIR}/bin:$PATH