name: Validate Commit Message AAMP 
on:
  pull_request_target:
    branches:
      - dev_sprint_25_2
      - feature/VPLAY-10292_new
      - feature/VPLAY-10292
    types: [ opened, reopened, edited, synchronize, unlocked ] 

jobs:
  validate-commit-message:
    name: commit-template-validation
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            
      - name: Executing Validation Script
        run: |
          python3 .github/commit_template_validation.py --newrev "${{ github.event.pull_request.head.sha }}" --message "${{ github.event.pull_request.title }}"
