name: L1 tests

on:
  pull_request:
    branches: [ develop, dev_sprint_25_2 ]

jobs:

  execute-unit-tests-on-pr:
    name: Runs all unit tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the aamp repository
      - name: Checkout aamp code
        uses: actions/checkout@v3
        
      # Install AAMP
      - name: Install AAMP (with apt fix)
        run: yes | ./install-aamp.sh -s -k file
        
      # Run L1 tests
      - name: Run unit tests
        working-directory: ./test/utests
        run: |
          ./run.sh 2>&1 | tee utest_run.log

      # Generate pretty test run output
      - name: Pretty test run output
        if: always()
        working-directory: ./test/utests
        run: |
          python3 parse_gtest_log.py utest_run.log
      
      # Publish test results
      - name: Publish L1 test results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: test/utests/build/ctest-results.xml
          reporter: java-junit
          
      # Upload artifact (test/utests/build/ctest-results.xml)
      - name: Upload test result file (test/utests)
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results-test-utests-${{ github.run_id }}
          path: test/utests/build/ctest-results.xml
          
      # Show failure
      - name: Show failure details (if any)
        # if: failure()
        run: tail -n 50 test/utests/build/ctest-results.xml || true

      # Install Middleware
      - name: Install Middleware PlayerInterface
        working-directory: ./middleware
        run: yes | ./install-middleware.sh -s subtec
        
      # Run L1 tests
      - name: Run unit tests
        working-directory: ./middleware/test/utests
        run: ./run.sh
      
      # Publish test results
      - name: Publish L1 test results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: middleware/test/utests/build/ctest-results.xml
          reporter: java-junit
          
      # Upload artifact (middleware/test/utests/build/ctest-results.xml)
      - name: Upload test result file (middleware/test/utests)
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results-middleware-utests-${{ github.run_id }}
          path: middleware/test/utests/build/ctest-results.xml
      
      # Show failure
      - name: Show failure details (if any)
        # if: failure()
        run: tail -n 50 middleware/test/utests/build/ctest-results.xml || true
