name: L1 tests

on:
  pull_request:
    branches: [ develop, test-branch ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}
  WORKSPACE: ${{ github.workspace }}
  CI_CONTAINER: ${{ secrets.CI_CONTAINER }}
  TEST_RESULTS_SERVER: ${{ secrets.TEST_RESULTS_SERVER }}

jobs:
  execute-unit-tests-on-pr:
    name: Runs all unit tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the aamp repository
      - name: Checkout aamp code
        uses: actions/checkout@v3
      
      # Install AAMP
      - name: Install AAMP
        run: yes | ./install-aamp.sh -s -k file
      
      # Run L1 tests
      - name: Run unit tests
        working-directory: ./test/utests
        run: ./run.sh
      
      # Publish test results
      - name: Publish L1 test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: test/utests/build/ctest-results.xml
          reporter: java-junit
      
      # Upload artifact (test/utests/build/ctest-results.xml)
      - name: Upload test result file
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results
          path: test/utests/build/ctest-results.xml
      
      # Show failure
      - name: Show test result (tail)
        if: failure()
        run: tail -n 50 test/utests/build/ctest-results.xml
        