name: Unit tests

on:
  pull_request:
    branches: [ develop, test-branch ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}
  WORKSPACE: ${{ github.workspace }}
  CI_CONTAINER: ${{ secrets.CI_CONTAINER }}
  TEST_RESULTS_SERVER: ${{ secrets.TEST_RESULTS_SERVER }}

jobs:
  execute-unit-tests-on-pr:
    name: Execute unit tests in gtest test suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout aamp code
        uses: actions/checkout@v3
        with:
            path: aamp

      - name: Run unit tests
        working-directory: ./aamp
        run: test/utests/run.sh

      # - name: Upload test results to automatic test result management system
      #   run: >
      #     gtest-json-result-push.py /tmp/Gtest_Report ${{ env.TEST_RESULTS_SERVER }} `pwd`