name: L1 tests

on:
  pull_request:
    branches: [ develop, dev_sprint_25_2 ]

jobs:
  execute-unit-tests-on-pr:
    name: Runs all unit tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the aamp repository
      - name: Checkout aamp code
        uses: actions/checkout@v3
      
      # Install AAMP
      - name: Install AAMP
        run: yes | ./install-aamp.sh -s -k file
      
      # Run L1 tests
      - name: Run unit tests
        working-directory: ./test/utests
        run: ./run.sh
      
      # Publish test results
      - name: Publish L1 test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: test/utests/build/ctest-results.xml
          reporter: java-junit
      
      # Upload artifact (test/utests/build/ctest-results.xml)
      - name: Upload test result file
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results
          path: test/utests/build/ctest-results.xml
      
            # Make install-middleware.sh executable
      - name: Make install-middleware.sh executable
        run: chmod +x ./aamp/middleware/install-middleware.sh
      
      # Install Middleware
      - name: Install Middleware Player Interface
        run: yes | ./aamp/middleware/install-middleware.sh -s -k file

      # Make run.sh executable
      - name: Make run.sh executable
        run: chmod +x ./aamp/middleware/test/utests/run.sh
        
      # Run L1 tests
      - name: Run unit tests
        working-directory: ./aamp/middleware/test/utests
        run: ./run.sh
      
      # Publish test results
      - name: Publish L1 test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: aamp/middleware/test/utests/build/ctest-results.xml
          reporter: java-junit
      
      # Upload artifact (middleware/test/utests/build/ctest-results.xml)
      - name: Upload test result file
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results
          path: aamp/middleware/test/utests/build/ctest-results.xml
            
      # Show failure
      - name: Show failure details (if any)
        if: failure()
        run: tail -n 50 test/utests/build/ctest-results.xml

      # Show failure
      - name: Show failure details (if any)
        if: failure()
        run: tail -n 50 aamp/middleware/test/utests/build/ctest-results.xml
