name: Unit tests

on:
  pull_request:
    branches: [ develop, main ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}
  WORKSPACE: ${{ github.workspace }}
  TEST_RESULTS_SERVER: ${{ secrets.TEST_RESULTS_SERVER }}

jobs:
  execute-unit-tests-on-pr:
    name: Execute unit tests in gtest test suite
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout aamp code
        uses: actions/checkout@v3
        with:
            path: aamp

      - name: Run unit tests
        run: /bin/bash aamp/test/run_ut.sh

      - name: Upload test results to automatic test result management system
        if: github.repository_owner == 'rdkcentral'
        run: |
          git config --global --add safe.directory `pwd`
          gtest-json-result-push.py /tmp/Gtest_Report ${{ env.TEST_RESULTS_SERVER }} `pwd`
